<Project Sdk="Aspire.AppHost.Sdk/13.4.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0ace8566-a78f-45c7-911e-a0ecf386537a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeStorage.Api\HomeStorage.Api.csproj" />
    <ProjectReference Include="..\HomeStorage.Web\HomeStorage.Web.csproj" />
  </ItemGroup>

</Project>
