@baseUrl=http://localhost:5000
@productId=1ec7a698-3893-4166-87bd-df8c63b0a044
@locationId=1

### Locations

GET {{baseUrl}}/locations
Content-Type: application/json

###

GET {{baseUrl}}/locations/{{locationId}}
Content-Type: application/json

###

POST {{baseUrl}}/locations
Content-Type: application/json

{
  "locationName": "Drawer in the wardrobe"
}

###

PUT {{baseUrl}}/locations/{{locationId}}
Content-Type: application/json

{
  "locationName": "Top drawer in the wardrobe"
}

###

DELETE {{baseUrl}}/locations/{{locationId}}
Content-Type: application/json

### Products

GET {{baseUrl}}/products
Content-Type: application/json

###

GET {{baseUrl}}/products/{{productId}}
Content-Type: application/json

###

POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Printer paper",
  "description": "A4",
  "producer": "Acme",
  "quantity": 5,
  "locationId": 1
}

###

PUT {{baseUrl}}/products/{{productId}}
Content-Type: application/json

{
  "name": "Printer paper",
  "description": "A4 80g",
  "producer": "Acme",
  "quantity": 3,
  "locationId": 1
}

###

DELETE {{baseUrl}}/products/{{productId}}
Content-Type: application/json
